import org.gradle.kotlin.dsl.support.kotlinCompilerOptions

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("org.openjfx.javafxplugin") version "0.1.0"
    id("io.realm.kotlin") version "1.16.0"
//    id("org.jetbrains.kotlinx.atomicfu") version "0.27.0"
    kotlin("jvm") version "1.9.24"

    //kotlin("jvm") version "2.1.0"
}

kotlin {
    jvmToolchain(17)
}

javafx {
    modules("javafx.graphics", "javafx.media", "javafx.fxml")
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.com.github.tulskiy.jkeymaster)
    api(libs.org.slf4j.slf4j.jdk14)
    //api(libs.org.openjfx.javafx.graphics)
    //api(libs.org.openjfx.javafx.media)
    //api(libs.org.openjfx.javafx.fxml)
    api(libs.org.json.json)
    implementation("io.realm.kotlin:library-base:1.16.0")
    implementation("org.jetbrains.kotlin:kotlin-reflect:1.9.24")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.0")
//    implementation("org.openjfx:javafx-fxml:23.0.1")
//    implementation("org.openjfx:javafx-graphics:23.0.1")
//    implementation("org.openjfx:javafx-media:23.0.1")

    implementation("org.openjfx:javafx-fxml:17.0.8")
    implementation("org.openjfx:javafx-graphics:17.0.8")
    implementation("org.openjfx:javafx-media:17.0.8")

    implementation("org.jetbrains.kotlinx:atomicfu:0.24.0")

    //id("org.jetbrains.kotlinx.atomicfu") version "0.27.0"
    //implementation("org.jetbrains.kotlinx.atomicfu:0.27.0")



}

tasks.withType<Jar> {

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    manifest {
        attributes["Main-Class"] = "Main"
    }

    from(configurations.compileClasspath.get().map { if (it.isDirectory()) it else zipTree(it) })
}

java {
    modularity.inferModulePath = false
}

group = "org.example"
version = "0.7.x"
description = "OsuMP3"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
