import org.gradle.kotlin.dsl.support.kotlinCompilerOptions

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("org.openjfx.javafxplugin") version "0.1.0"
    id("io.realm.kotlin") version "1.16.0"
    kotlin("jvm") version "1.9.24"
}

sourceSets {
    main {
        resources {
            srcDirs( "src/main/resources")
        }
    }
}

kotlin {
    jvmToolchain(17)
}

javafx {
    modules("javafx.graphics", "javafx.media", "javafx.fxml")
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
    maven {
        url = uri("https://maven.google.com/")
    }
}

dependencies {
    api(libs.com.github.tulskiy.jkeymaster)
    api(libs.org.slf4j.slf4j.jdk14)
    api(libs.org.json.json)


    implementation("io.realm.kotlin:library-base:1.16.0")
    implementation("org.jetbrains.kotlin:kotlin-reflect:1.9.24")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.0")

    // Java FX 22 requires minimum JDK 17
    implementation("org.openjfx:javafx-fxml:22.0.2")
    implementation("org.openjfx:javafx-graphics:22.0.2")
    implementation("org.openjfx:javafx-media:22.0.2")

    // Needed by Realm DB
    implementation("org.jetbrains.kotlinx:atomicfu:0.24.0")

    // https://mvnrepository.com/artifact/com.tagtraum/audioplayer4j-complete
    implementation("com.tagtraum:audioplayer4j-complete:0.9.4")

    // Temporarily removed in favor of local fix.
    // See libs\com\tagtraum\ffsampledsp\README.md
    // https://mvnrepository.com/artifact/com.tagtraum/ffsampledsp-complete
    //implementation("com.tagtraum:ffsampledsp-complete:0.9.53")

    implementation(files("libs\\com\\tagtraum\\ffsampledsp\\ffsampledsp-complete-0.9.53-fix.jar"))

}

tasks.withType<Jar> {

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    manifest {
        attributes["Main-Class"] = "osu_mp3.Main"
    }

    from(configurations.compileClasspath.get().map { if (it.isDirectory()) it else zipTree(it) })
}

java {
    modularity.inferModulePath = false
}

group = "org.example"
version = "0.7.x"
description = "OsuMP3"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
